### PR TITLE
4.14.1

### PR DESCRIPTION
**Pull request by ericgaspar**
## Problem

- *Description of why you made this PR*

## Solution

- *And how do you fix that problem*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Comment by rodinux** [comment]
Hello @ericgaspar , this update seems working... Perhaps I should try, making first a backup... Do you think it is a good idea ?

**Comment by ericgaspar** [comment]
Well no it is not working... A layer of extra security as been added to Cryptpad. We really need to work on the NGINX config file according to the proposed model. https://github.com/xwiki-labs/cryptpad/blob/main/docs/example.nginx.conf

our NGINX configuration is minimal :/

**Comment by rodinux** [comment]
Ok... not easy...

**Pull request merged**
