### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by Ddataa**
## Problem

- package v1 

## Solution

- package v2

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by ericgaspar** [comment]
Do we want to regenerate the `config.js` file on upgrade (admin keys will be lost) or just make sure the sandbox domain is properly configured?

**Comment by ericgaspar** [comment]
!testme

**Comment by Ddataa** [comment]
we don't need to regenerate the config on upgrade

**Comment by Ddataa** [comment]
hum actually not
if sandbox was not at installation then it won't have it...

**Comment by Ddataa** [comment]
shall we be reading the value of admin key and re write it in the new config file instead ?

**Comment by Ddataa** [comment]
and `supportMailboxPublicKey` as well

**Comment by Ddataa** [comment]
@ericgaspar shall we correct those in another PR maybe ?

**Comment by Ddataa** [comment]
!testme

**Review by ericgaspar — APPROVED** [review]

**Pull request merged**
