### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by ericgaspar**
- Upgrade to version 4.1.0

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Review by tituspijean — APPROVED** [review]
LGTM!
What do you thing about silencing the build process with `ynh_exec_warn_less`?

**Comment by ericgaspar** [comment]
Looks quiet silent to me https://ci-apps-dev.yunohost.org/ci/job/274

**Comment by tituspijean** [comment]
Ha indeed, it was the install of the older version which was throwing build warnings.

**Pull request merged**
