### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by frju365**
## Problem
- Merge upstream

## Solution
- **

## PR Status
- [x] Code finished.
- [x] Tested with Package_check.
- [x] Fix or enhancement tested.
- [x] Upgrade from last version tested.
- [x] Can be reviewed and tested.

## Package_check results
---
*If you have access to [App Continuous Integration for packagers](https://yunohost.org/#/packaging_apps_ci) you can provide a link to the package_check results like below, replacing '-NUM-' in this link by the PR number and USERNAME by your username on the ci-apps-dev. Or you provide a screenshot or a pastebin of the results*

[Build Status/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/cryptpad_ynh%20PR-NUM-%20(USERNAME)/)

### CODE REVIEW

**Comment by ericgaspar** [comment]
Shall we merge to master #45 and push #46 to testing?

**Comment by alexAubin** [comment]
@ericgaspar  : I'd say, if the CI is happy with #46 and there's no tricky major change in the upstream or whatever, let's close #45 and merge #46 directly in master ...

**Comment by alexAubin** [comment]
(Or I mean even #48 ... )

**Comment by ericgaspar** [comment]
absolutely

**Comment by ericgaspar** [comment]
@frju365 well, all signals are nominal, green button can be pressed 🚀

**Comment by frju365** [comment]
Ok. Close this and merge other :) COmpletely agree

**Pull request closed without merging**
